#!/bin/bash
tmp_branch=tmp_deploy
default_stage=frontend
STAGE=${STAGE:-$default_stage}
HOST=iq300-dev.ru
current_branch=$(git symbolic-ref --short -q HEAD)
git remote remove $STAGE
git remote add $STAGE dokku@$HOST:$STAGE
git branch -D $tmp_branch
git checkout -b $tmp_branch
rm -rf package.json gulpfile.* bower.json app Gemfile Gemfile.lock Guardfile Rakefile config/ config.rb config.ru data/
cp -r dist/* .
cp -r build/* .
git add -A
git commit -m 'build'
git push -f $STAGE $tmp_branch:master
echo return to branch $current_branch
git checkout $current_branch
open "http://"$STAGE"."$HOST
npm install
bower install

