#!/bin/bash
tmp_branch=tmp_deploy
default_stage=frontend
STAGE=${STAGE:-$default_stage}
current_branch=$(git symbolic-ref --short -q HEAD)
git remote add $STAGE dokku@iq300-dev.com:$STAGE
git branch -D $tmp_branch
git checkout -b $tmp_branch
rm -rf app Gemfile Gemfile.lock Guardfile Rakefile config/ config.rb config.ru data/
mv dist/* .
git add -A
git commit -m 'build'
git push -f $STAGE $tmp_branch:master
echo return to branch $current_branch
git checkout $current_branch


